-- EasyWin Import: Reference Tables
SET client_encoding = 'UTF8';

TRUNCATE regioni CASCADE;
INSERT INTO regioni (id, nome, attivo) VALUES (1, 'Marche', TRUE);
INSERT INTO regioni (id, nome, attivo) VALUES (2, 'Abruzzo', TRUE);
INSERT INTO regioni (id, nome, attivo) VALUES (3, 'Basilicata', TRUE);
INSERT INTO regioni (id, nome, attivo) VALUES (4, 'Molise', TRUE);
INSERT INTO regioni (id, nome, attivo) VALUES (5, 'Trentino Alto Adige', TRUE);
INSERT INTO regioni (id, nome, attivo) VALUES (6, 'Puglia', TRUE);
INSERT INTO regioni (id, nome, attivo) VALUES (7, 'Calabria', TRUE);
INSERT INTO regioni (id, nome, attivo) VALUES (8, 'Campania', TRUE);
INSERT INTO regioni (id, nome, attivo) VALUES (9, 'Lazio', TRUE);
INSERT INTO regioni (id, nome, attivo) VALUES (10, 'Sardegna', TRUE);
INSERT INTO regioni (id, nome, attivo) VALUES (11, 'Sicilia', TRUE);
INSERT INTO regioni (id, nome, attivo) VALUES (12, 'Toscana', TRUE);
INSERT INTO regioni (id, nome, attivo) VALUES (13, 'Piemonte', TRUE);
INSERT INTO regioni (id, nome, attivo) VALUES (14, 'Emilia Romagna', TRUE);
INSERT INTO regioni (id, nome, attivo) VALUES (15, 'Friuli Venezia Giulia', TRUE);
INSERT INTO regioni (id, nome, attivo) VALUES (16, 'Valle d''Aosta', TRUE);
INSERT INTO regioni (id, nome, attivo) VALUES (17, 'Veneto', TRUE);
INSERT INTO regioni (id, nome, attivo) VALUES (18, 'Liguria', TRUE);
INSERT INTO regioni (id, nome, attivo) VALUES (19, 'Lombardia', TRUE);
INSERT INTO regioni (id, nome, attivo) VALUES (20, 'Umbria', TRUE);
INSERT INTO regioni (id, nome, attivo) VALUES (21, 'Sconosciuta', TRUE);
SELECT setval('regioni_id_seq', (SELECT COALESCE(MAX(id),0) FROM regioni));

TRUNCATE province CASCADE;
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (1, 'Ancona', 'AN', 1, 42, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (2, 'Macerata', 'MC', 1, 43, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (3, 'Pesaro Urbino', 'PU', 1, 41, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (4, 'Ascoli Piceno', 'AP', 1, 44, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (5, 'Alessandria', 'AL', 13, 6, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (6, 'Asti', 'AT', 13, 5, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (7, 'Biella', 'BI', 13, 96, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (8, 'Cuneo', 'CN', 13, 4, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (9, 'Novara', 'NO', 13, 3, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (10, 'Vercelli', 'VC', 13, 2, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (11, 'Torino', 'TO', 13, 1, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (12, 'Agrigento', 'AG', 11, 84, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (13, 'Caltanissetta', 'CL', 11, 85, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (14, 'Catania', 'CT', 11, 87, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (15, 'Enna', 'EN', 11, 86, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (16, 'Messina', 'ME', 11, 83, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (17, 'Palermo', 'PA', 11, 82, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (18, 'Ragusa', 'RG', 11, 88, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (19, 'Siracusa', 'SR', 11, 89, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (20, 'Trapani', 'TP', 11, 81, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (21, 'Catanzaro', 'CZ', 7, 79, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (22, 'Cosenza', 'CS', 7, 78, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (23, 'Crotone', 'KR', 7, 101, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (24, 'Reggio Calabria', 'RC', 7, 80, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (25, 'Vibo Valentia', 'VV', 7, 102, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (26, 'Verbania', 'VB', 13, 103, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (27, 'Matera', 'MT', 3, 77, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (28, 'Potenza', 'PZ', 3, 76, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (29, 'Bari', 'BA', 6, 72, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (30, 'Brindisi', 'BR', 6, 74, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (31, 'Foggia', 'FG', 6, 71, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (32, 'Lecce', 'LE', 6, 75, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (33, 'Taranto', 'TA', 6, 73, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (34, 'Avellino', 'AV', 8, 64, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (35, 'Benevento', 'BN', 8, 62, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (36, 'Caserta', 'CE', 8, 61, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (37, 'Napoli', 'NA', 8, 63, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (38, 'Salerno', 'SA', 8, 65, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (39, 'Frosinone', 'FR', 9, 60, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (40, 'Latina', 'LT', 9, 59, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (41, 'Rieti', 'RI', 9, 57, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (42, 'Roma', 'RM', 9, 58, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (43, 'Viterbo', 'VT', 9, 56, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (44, 'Chieti', 'CH', 2, 69, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (45, 'L''Aquila', 'AQ', 2, 66, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (46, 'Pescara', 'PE', 2, 68, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (47, 'Teramo', 'TE', 2, 67, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (48, 'Arezzo', 'AR', 12, 51, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (49, 'Firenze', 'FI', 12, 48, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (50, 'Grosseto', 'GR', 12, 53, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (51, 'Livorno', 'LI', 12, 49, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (52, 'Lucca', 'LU', 12, 46, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (53, 'Massa Carrara', 'MS', 12, 45, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (54, 'Pisa', 'PI', 12, 50, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (55, 'Pistoia', 'PT', 12, 47, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (56, 'Siena', 'SI', 12, 52, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (57, 'Bologna', 'BO', 14, 37, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (58, 'Ferrara', 'FE', 14, 38, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (59, 'Forlì Cesena', 'FC', 14, 40, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (60, 'Modena', 'MO', 14, 36, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (61, 'Parma', 'PR', 14, 34, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (62, 'Piacenza', 'PC', 14, 33, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (63, 'Ravenna', 'RA', 14, 39, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (64, 'Reggio Emilia', 'RE', 14, 35, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (65, 'Rimini', 'RN', 14, 99, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (66, 'Belluno', 'BL', 17, 25, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (67, 'Padova', 'PD', 17, 28, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (68, 'Rovigo', 'RO', 17, 29, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (69, 'Treviso', 'TV', 17, 26, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (70, 'Venezia', 'VE', 17, 27, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (71, 'Verona', 'VR', 17, 23, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (72, 'Vicenza', 'VI', 17, 24, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (73, 'Gorizia', 'GO', 15, 31, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (74, 'Pordenone', 'PN', 15, 93, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (75, 'Udine', 'UD', 15, 30, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (76, 'Trieste', 'TS', 15, 32, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (77, 'Aosta', 'AO', 16, 7, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (78, 'Cagliari', 'CA', 10, 92, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (79, 'Nuoro', 'NU', 10, 91, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (80, 'Oristano', 'OR', 10, 95, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (81, 'Sassari', 'SS', 10, 90, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (82, 'Genova', 'GE', 18, 10, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (83, 'Imperia', 'IM', 18, 8, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (84, 'Savona', 'SV', 18, 9, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (85, 'La Spezia', 'SP', 18, 11, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (86, 'Isernia', 'IS', 4, 94, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (87, 'Campobasso', 'CB', 4, 70, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (88, 'Perugia', 'PG', 20, 54, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (89, 'Terni', 'TR', 20, 55, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (90, 'Bergamo', 'BG', 19, 16, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (91, 'Brescia', 'BS', 19, 17, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (92, 'Como', 'CO', 19, 13, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (93, 'Cremona', 'CR', 19, 19, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (94, 'Lecco', 'LC', 19, 97, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (95, 'Lodi', 'LO', 19, 98, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (96, 'Mantova', 'MN', 19, 20, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (97, 'Milano', 'MI', 19, 15, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (98, 'Pavia', 'PV', 19, 18, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (99, 'Sondrio', 'SO', 19, 14, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (100, 'Varese', 'VA', 19, 12, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (101, 'Trento', 'TN', 5, 22, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (102, 'Bolzano', 'BZ', 5, 21, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (103, 'Prato', 'PO', 12, 100, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (104, 'Carbonia Iglesias', 'CI', 10, 107, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (105, 'Medio Campidano', 'VS', 10, 106, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (106, 'Ogliastra', 'OG', 10, 105, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (107, 'Olbia Tempio', 'OT', 10, 104, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (108, 'Sconosciuta', 'YY', 21, NULL, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (109, 'Monza e Brianza', 'MB', 19, 108, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (110, 'Fermo', 'FM', 1, 109, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (185, 'Barletta-Andria-Trani', 'BT', 6, 110, TRUE);
INSERT INTO province (id, nome, sigla, id_regione, codice_istat, attivo) VALUES (186, 'Sud Sardegna', 'SU', 10, 111, TRUE);
SELECT setval('province_id_seq', (SELECT COALESCE(MAX(id),0) FROM province));

TRUNCATE criteri CASCADE;
INSERT INTO criteri (id, nome, attivo) VALUES (1, 'Media (art.86,122 c. 9)', TRUE);
INSERT INTO criteri (id, nome, attivo) VALUES (2, 'Massimo Ribasso (ART. 86,87,88 D.LGS. 163/2006)', TRUE);
INSERT INTO criteri (id, nome, attivo) VALUES (3, 'Offerta Economicamente Più Vantaggiosa', TRUE);
INSERT INTO criteri (id, nome, attivo) VALUES (4, 'Media Valle D''Aosta (art.86,122 c. 9,art. 25 c. 7 L.R. 12/96)', TRUE);
INSERT INTO criteri (id, nome, attivo) VALUES (5, 'Non Indicato', TRUE);
INSERT INTO criteri (id, nome, attivo) VALUES (7, 'Media Trentino (50° percentile)', TRUE);
INSERT INTO criteri (id, nome, attivo) VALUES (8, 'Procedura Publiacqua spa di Firenze', TRUE);
INSERT INTO criteri (id, nome, attivo) VALUES (9, 'Media Pura (Friuli Venezia Giulia)', TRUE);
INSERT INTO criteri (id, nome, attivo) VALUES (10, 'Esclusione Automatica Delle Offerte Anomale (ART. 95 C.4, ART. 97 C. 2, ART. 97 C. 8 D.LGS. 50/2016)', TRUE);
INSERT INTO criteri (id, nome, attivo) VALUES (11, 'Massimo ribasso (ART. 95 C. 4, ART. 97 C.2 D. LGS. 50/2016)', TRUE);
INSERT INTO criteri (id, nome, attivo) VALUES (12, 'Esclusione Automatica Delle Offerte Anomale (DL N. 32/2019 "Sblocca cantieri")', TRUE);
INSERT INTO criteri (id, nome, attivo) VALUES (13, 'Massimo Ribasso (DL 32/2019 "Sblocca Cantieri")', TRUE);
INSERT INTO criteri (id, nome, attivo) VALUES (14, 'Esclusione automatica delle offerte anomale (LEGGE REGIONALE SICILIANA N. 13 DEL 19-07-2019)', TRUE);
INSERT INTO criteri (id, nome, attivo) VALUES (15, 'Esclusione Automatica Delle Offerte Anomale (DL N. 76 del 16-07-20 "Semplificazioni")', TRUE);
INSERT INTO criteri (id, nome, attivo) VALUES (16, 'Massimo Ribasso (DL N. 76 del 16-07-20 "Semplificazioni")', TRUE);
INSERT INTO criteri (id, nome, attivo) VALUES (17, 'Esclusione Automatica Delle Offerte Anomale (All. II.2 e art. 54 del D.Lgs 36/2023)', TRUE);
INSERT INTO criteri (id, nome, attivo) VALUES (18, 'Massimo Ribasso (All. II.2 e art. 54 del D.Lgs 36/2023)', TRUE);
INSERT INTO criteri (id, nome, attivo) VALUES (19, 'Esclusione Automatica Delle Offerte Anomale (All. II.2 e art. 54 del D.Lgs 36/2023) - METODO A', TRUE);
INSERT INTO criteri (id, nome, attivo) VALUES (20, 'Esclusione Automatica Delle Offerte Anomale (All. II.2 e art. 54 del D.Lgs 36/2023) - METODO B', TRUE);
INSERT INTO criteri (id, nome, attivo) VALUES (21, 'Esclusione Automatica Delle Offerte Anomale (All. II.2 e art. 54 del D.Lgs 36/2023) - METODO C', TRUE);
INSERT INTO criteri (id, nome, attivo) VALUES (22, 'Massimo Ribasso (All. II.2 e art. 54 del D.Lgs 36/2023) - METODO A', TRUE);
INSERT INTO criteri (id, nome, attivo) VALUES (23, 'Massimo Ribasso (All. II.2 e art. 54 del D.Lgs 36/2023) - METODO B', TRUE);
INSERT INTO criteri (id, nome, attivo) VALUES (24, 'Massimo Ribasso (All. II.2 e art. 54 del D.Lgs 36/2023) - METODO C', TRUE);
SELECT setval('criteri_id_seq', (SELECT COALESCE(MAX(id),0) FROM criteri));

TRUNCATE tipologia_bandi CASCADE;
INSERT INTO tipologia_bandi (id, nome, attivo) VALUES (1, 'Procedura Aperta', TRUE);
INSERT INTO tipologia_bandi (id, nome, attivo) VALUES (2, 'Manifestazione d''interesse / Indagine di mercato', TRUE);
INSERT INTO tipologia_bandi (id, nome, attivo) VALUES (3, 'Procedura Ristretta Semplificata', FALSE);
INSERT INTO tipologia_bandi (id, nome, attivo) VALUES (4, 'Procedura Negoziata', TRUE);
INSERT INTO tipologia_bandi (id, nome, attivo) VALUES (5, 'Procedura Telematica', FALSE);
INSERT INTO tipologia_bandi (id, nome, attivo) VALUES (6, 'Leasing in Costruendo', FALSE);
INSERT INTO tipologia_bandi (id, nome, attivo) VALUES (7, 'Project Financing', FALSE);
INSERT INTO tipologia_bandi (id, nome, attivo) VALUES (8, 'Informazione Preliminare', TRUE);
INSERT INTO tipologia_bandi (id, nome, attivo) VALUES (9, 'Indagine di Mercato', FALSE);
INSERT INTO tipologia_bandi (id, nome, attivo) VALUES (10, 'Concorso di idee', FALSE);
INSERT INTO tipologia_bandi (id, nome, attivo) VALUES (11, 'Albo Fornitori', TRUE);
INSERT INTO tipologia_bandi (id, nome, attivo) VALUES (12, 'Incarico Professionale', TRUE);
INSERT INTO tipologia_bandi (id, nome, attivo) VALUES (13, 'Non Indicato', TRUE);
INSERT INTO tipologia_bandi (id, nome, attivo) VALUES (14, 'Piani Triennali', TRUE);
SELECT setval('tipologia_bandi_id_seq', (SELECT COALESCE(MAX(id),0) FROM tipologia_bandi));

TRUNCATE tipologia_gare CASCADE;
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (1, 'Procedura aperta o procedura ristretta a media (Art. 86, 122 C.9 D.LGS. 163/2006)', TRUE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (2, 'Procedura Negoziata o Procedura Ristretta Semplificata o trattativa privata o cottimo fiduciario a media (Art. 86, 122 C.9 D.LGS. 163/2006)', TRUE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (3, 'Procedura aperta o procedura ristretta al massimo ribasso', TRUE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (4, 'Procedura Negoziata o Procedura Ristretta Semplificata o trattativa privata o cottimo fiduciario al massimo ribasso', TRUE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (5, 'Procedura aperta ad offerta economicamente più vantaggiosa', TRUE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (7, 'Procedura aperta o procedura ristretta a media Valle d''Aosta', TRUE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (8, 'Procedura Publiacqua spa di Firenze', TRUE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (9, 'Project Financing', FALSE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (10, 'Incarico Professionale', FALSE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (11, 'Progettazione', FALSE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (12, 'Altro', FALSE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (13, 'Procedura aperta o procedura ristretta a media Friuli Venezia Giulia', TRUE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (14, 'Procedura aperta o procedura ristretta a media Trentino', TRUE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (15, 'Procedura aperta con esclusione automatica delle offerte anomale TIPO A', TRUE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (16, 'Procedura aperta con esclusione automatica delle offerte anomale TIPO B', TRUE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (17, 'Procedura aperta con esclusione automatica delle offerte anomale TIPO C', TRUE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (18, 'Procedura aperta con esclusione automatica delle offerte anomale TIPO D', TRUE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (19, 'Procedura aperta con esclusione automatica delle offerte anomale TIPO E', TRUE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (20, 'Procedura aperta con esclusione automatica delle offerte anomale (aggiudicata al massimo ribasso)', TRUE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (21, 'Procedura negoziata con esclusione automatica delle offerte anomale TIPO A', TRUE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (22, 'Procedura negoziata con esclusione automatica delle offerte anomale TIPO B', TRUE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (23, 'Procedura negoziata con esclusione automatica delle offerte anomale TIPO C', TRUE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (24, 'Procedura negoziata con esclusione automatica delle offerte anomale TIPO D', TRUE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (25, 'Procedura negoziata con esclusione automatica delle offerte anomale TIPO E', TRUE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (26, 'Procedura negoziata con esclusione automatica delle offerte anomale (aggiudicata al massimo ribasso)', TRUE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (27, 'Procedura Negoziata ad offerta economicamente più vantaggiosa', TRUE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (28, 'In attesa di definizione', TRUE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (29, 'Procedura aperta a massimo ribasso TIPO A', TRUE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (30, 'Procedura aperta a massimo ribasso TIPO B', TRUE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (31, 'Procedura aperta a massimo ribasso TIPO C', TRUE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (32, 'Procedura aperta a massimo ribasso TIPO D', TRUE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (33, 'Procedura aperta a massimo ribasso TIPO E', TRUE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (34, 'Procedura negoziata a massimo ribasso TIPO A', TRUE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (35, 'Procedura negoziata a massimo ribasso TIPO B', TRUE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (36, 'Procedura negoziata a massimo ribasso TIPO C', TRUE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (37, 'Procedura negoziata a massimo ribasso TIPO D', TRUE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (38, 'Procedura negoziata a massimo ribasso TIPO E', TRUE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (39, 'Procedura aperta in attesa di definizione', TRUE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (40, 'Procedura negoziata in attesa di definizione', TRUE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (41, 'Procedura aperta con esclusione automatica delle offerte anomale (ART. 95 C.4, ART. 97 C.2, ART. 97 C. 8)', TRUE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (42, 'Procedura negoziata con esclusione automatica delle offerte anomale (ART. 95 C.4, ART. 97 C.2, ART. 97 C. 8)', TRUE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (43, 'Procedura aperta con esclusione automatica delle offerte anomale (DL 32/2019 "Sblocca Cantieri")', TRUE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (44, 'Procedura negoziata con esclusione automatica delle offerte anomale (DL 32/2019 "Sblocca Cantieri")', TRUE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (45, 'Procedura aperta a massimo ribasso (DL 32/2019 "Sblocca Cantieri")', TRUE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (46, 'Procedura negoziata a massimo ribasso (DL 32/2019 "Sblocca Cantieri")', TRUE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (47, 'Procedura aperta LEGGE REGIONALE SICILIANA N. 13 DEL 19-07-2019', TRUE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (48, 'Procedura negoziata LEGGE REGIONALE SICILIANA N. 13 DEL 19-07-2019', TRUE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (49, 'Procedura aperta con esclusione automatica delle offerte anomale (DL 76 del 16-07-20 "Semplificazioni")', TRUE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (50, 'Procedura negoziata con esclusione automatica delle offerte anomale (DL 76 del 16-07-20 "Semplificazioni")', TRUE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (51, 'Procedura aperta a massimo ribasso (DL 76 del 16-07-20 "Semplificazioni")', TRUE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (52, 'Procedura negoziata a massimo ribasso (DL 76 del 16-07-20 "Semplificazioni")', TRUE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (53, 'Procedura aperta con esclusione automatica delle offerte anomale (All. II.2 e art. 54 del D.Lgs 36/2023) - METODO A', TRUE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (54, 'Procedura aperta con esclusione automatica delle offerte anomale (All. II.2 e art. 54 del D.Lgs 36/2023) - METODO B', TRUE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (55, 'Procedura aperta con esclusione automatica delle offerte anomale (All. II.2 e art. 54 del D.Lgs 36/2023) - METODO C', TRUE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (56, 'Procedura aperta con esclusione automatica delle offerte anomale (All. II.2 e art. 54 del D.Lgs 36/2023) (Aggiudicata al massimo ribasso)', TRUE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (57, 'Procedura negoziata con esclusione automatica delle offerte anomale (All. II.2 e art. 54 del D.Lgs 36/2023) - METODO A', TRUE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (58, 'Procedura negoziata con esclusione automatica delle offerte anomale (All. II.2 e art. 54 del D.Lgs 36/2023) - METODO B', TRUE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (59, 'Procedura negoziata con esclusione automatica delle offerte anomale (All. II.2 e art. 54 del D.Lgs 36/2023) - METODO C', TRUE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (60, 'Procedura negoziata con esclusione automatica delle offerte anomale (All. II.2 e art. 54 del D.Lgs 36/2023) (Aggiudicata al massimo ribasso)', TRUE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (61, 'Procedura aperta a massimo ribasso (All. II.2 e art. 54 del D.Lgs 36/2023) - METODO A', TRUE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (62, 'Procedura aperta a massimo ribasso (All. II.2 e art. 54 del D.Lgs 36/2023) - METODO B', TRUE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (63, 'Procedura aperta a massimo ribasso (All. II.2 e art. 54 del D.Lgs 36/2023) - METODO C', TRUE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (64, 'Procedura negoziata a massimo ribasso (All. II.2 e art. 54 del D.Lgs 36/2023) - METODO A', TRUE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (65, 'Procedura negoziata a massimo ribasso (All. II.2 e art. 54 del D.Lgs 36/2023) - METODO B', TRUE);
INSERT INTO tipologia_gare (id, nome, attivo) VALUES (66, 'Procedura negoziata a massimo ribasso (All. II.2 e art. 54 del D.Lgs 36/2023) - METODO C', TRUE);
SELECT setval('tipologia_gare_id_seq', (SELECT COALESCE(MAX(id),0) FROM tipologia_gare));

TRUNCATE tipo_dati_gara CASCADE;
INSERT INTO tipo_dati_gara (id, tipo, priority, attivo) VALUES (1, 'Completa', 1, TRUE);
INSERT INTO tipo_dati_gara (id, tipo, priority, attivo) VALUES (2, 'Elenco aziende Partecipanti e Ribasso solo del Vincitore', 2, TRUE);
INSERT INTO tipo_dati_gara (id, tipo, priority, attivo) VALUES (3, 'N° Partecipanti e Ribasso del Vincitore', 3, TRUE);
INSERT INTO tipo_dati_gara (id, tipo, priority, attivo) VALUES (4, 'Nessun partecipante', 4, TRUE);
INSERT INTO tipo_dati_gara (id, tipo, priority, attivo) VALUES (5, 'Gara non conclusa', 5, TRUE);
SELECT setval('tipo_dati_gara_id_seq', (SELECT COALESCE(MAX(id),0) FROM tipo_dati_gara));

TRUNCATE piattaforme CASCADE;
INSERT INTO piattaforme (id, nome, url, attivo) VALUES (0, 'Nessuna', NULL, TRUE);
INSERT INTO piattaforme (id, nome, url, attivo) VALUES (1, 'Non indicata', NULL, TRUE);
INSERT INTO piattaforme (id, nome, url, attivo) VALUES (2, 'MEPA', 'https://www.acquistinretepa.it/opencms/opencms/', TRUE);
INSERT INTO piattaforme (id, nome, url, attivo) VALUES (3, 'Sintel', 'https://www.sintel.regione.lombardia.it/fwep/', TRUE);
INSERT INTO piattaforme (id, nome, url, attivo) VALUES (4, 'START by FABER', 'https://start.toscana.it/', TRUE);
INSERT INTO piattaforme (id, nome, url, attivo) VALUES (5, 'Intercent-ER', 'http://intercenter.regione.emilia-romagna.it/', TRUE);
INSERT INTO piattaforme (id, nome, url, attivo) VALUES (6, 'BravoSolutions', 'http://bravosolution.it/', TRUE);
INSERT INTO piattaforme (id, nome, url, attivo) VALUES (7, 'Empulia', 'https://eprocurement.empulia.it/portale/LoginEsterno.asp', TRUE);
INSERT INTO piattaforme (id, nome, url, attivo) VALUES (8, 'FABER', 'https://www.acea.it/it#', TRUE);
INSERT INTO piattaforme (id, nome, url, attivo) VALUES (10, 'Asmecomm by TuttoGare', 'https://piattaforma.asmecomm.it/gare/index.php', TRUE);
INSERT INTO piattaforme (id, nome, url, attivo) VALUES (14, 'TuttoGare', 'https://gare.adspmam.it/accesso.php', TRUE);
INSERT INTO piattaforme (id, nome, url, attivo) VALUES (15, 'DigitalPA', 'https://www.digitalpa.it/', TRUE);
INSERT INTO piattaforme (id, nome, url, attivo) VALUES (16, 'MAGGIOLI', 'http://www.appaltiecontratti.it/', TRUE);
INSERT INTO piattaforme (id, nome, url, attivo) VALUES (24, 'CONSIP', 'http://www.consip.it/bandi-di-gara', TRUE);
INSERT INTO piattaforme (id, nome, url, attivo) VALUES (25, 'eAppaltiFVG by BravoSolutions', 'https://eappalti.regione.fvg.it/web/index.html', TRUE);
INSERT INTO piattaforme (id, nome, url, attivo) VALUES (29, 'INVA by FABER', 'https://inva.i-faber.com/', TRUE);
INSERT INTO piattaforme (id, nome, url, attivo) VALUES (32, 'MERCURIO', 'http://www.mercurio.provincia.tn.it/', TRUE);
INSERT INTO piattaforme (id, nome, url, attivo) VALUES (34, 'NET4MARKET', 'https://www.net4market.com/', TRUE);
INSERT INTO piattaforme (id, nome, url, attivo) VALUES (36, 'PIATTAFORMA COMUNE', NULL, TRUE);
INSERT INTO piattaforme (id, nome, url, attivo) VALUES (37, 'PIATTAFORMA CUC', NULL, TRUE);
INSERT INTO piattaforme (id, nome, url, attivo) VALUES (38, 'PIATTAFORMA ENTE', NULL, TRUE);
INSERT INTO piattaforme (id, nome, url, attivo) VALUES (42, 'SardegnaCAT by BravoSolutions', 'https://www.sardegnacat.it/esop/ita-ras-host/public/web/login.jst', TRUE);
INSERT INTO piattaforme (id, nome, url, attivo) VALUES (46, 'TRASPARE', 'https://www.traspare.com/', TRUE);
INSERT INTO piattaforme (id, nome, url, attivo) VALUES (47, 'Asmepal by TuttoGare', 'https://piattaforma.asmel.eu/archivio_gare/', TRUE);
SELECT setval('piattaforme_id_seq', (SELECT COALESCE(MAX(id),0) FROM piattaforme));